/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;

/**
 *
 * @author Joel  / Thomas / Raphael
 */
public class EtatContrat extends javax.swing.JFrame {
    private Client client;
    String contrat = null;
    private ArrayList<Materiel> lesMateriaux = new ArrayList<>();
    private ArrayList<ContratMaintenance> lesContrats = new ArrayList<>();
    
    public EtatContrat(Client client) throws SQLException{
        this.client = client;
        initComponents();
        //getContrat();
    }
    /**
     * Creates new form EtatContrat
     */
    
    public EtatContrat() throws SQLException {
        initComponents();
        //getContrat(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupRadioButton = new javax.swing.ButtonGroup();
        btnSoumettre1 = new javax.swing.JButton();
        lblNomClient = new javax.swing.JLabel();
        ContratExpire = new javax.swing.JLabel();
        cbMaterielVendu = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnSoumettre = new javax.swing.JButton();
        btnRetour = new javax.swing.JButton();

        btnSoumettre1.setText("Soumettre");
        btnSoumettre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoumettre1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNomClient.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        ContratExpire.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ContratExpire.setText("Matériels qui ont expirés");

        cbMaterielVendu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaterielVenduActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Voulez vous vraiment renouveler ce contrat");

        btnSoumettre.setText("Soumettre");
        btnSoumettre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoumettreActionPerformed(evt);
            }
        });

        btnRetour.setText("Retour");
        btnRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ContratExpire, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbMaterielVendu, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(lblNomClient))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRetour)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnSoumettre)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblNomClient)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContratExpire)
                    .addComponent(cbMaterielVendu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btnSoumettre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnRetour)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMaterielVenduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaterielVenduActionPerformed
        getContrat(evt);
    }//GEN-LAST:event_cbMaterielVenduActionPerformed

    private void btnSoumettreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoumettreActionPerformed
        try {
            Connecting connection = new Connecting();
            String contratSelectionne = contrat;
        for(ContratMaintenance contrat: lesContrats){
            if(String.valueOf(contrat.getNumContrat()) == contratSelectionne){
                connection.rangerDansBase(contrat);
            }
        }
        } catch (SQLException ex) {
            Logger.getLogger(EtatContrat.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnSoumettreActionPerformed

    private void btnSoumettre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoumettre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSoumettre1ActionPerformed

    private void btnRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourActionPerformed
        this.setVisible(false);
        try {
            new SearchClient().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(EtatContrat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRetourActionPerformed
private String getContrat(ActionEvent evt){
    
    if (cbMaterielVendu.getSelectedItem() != null){
        contrat = cbMaterielVendu.toString();
    }
    return contrat;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EtatContrat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EtatContrat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EtatContrat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EtatContrat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new EtatContrat().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(EtatContrat.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
        
        
        
        
    }
    /*private void getContrat() throws SQLException{
        Connecting connection = new Connecting();
        lesContrats = (ArrayList<ContratMaintenance>) connection.chargerDepuisBase(client.getNumClient(), "Contrat");
        System.out.println("got in");
        ArrayList<ContratMaintenance> expire = new ArrayList();
        for (ContratMaintenance unContrat : lesContrats){
            System.out.println("le numero du contrat :" + unContrat.getNumContrat());  
            if (unContrat.getNbrJourAvantEcheance() <= 0) {
                cbMaterielVendu.addItem(Integer.toString(unContrat.getNumContrat()));
            
                }
        }
    }*/
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ContratExpire;
    private javax.swing.JButton btnRetour;
    private javax.swing.JButton btnSoumettre;
    private javax.swing.JButton btnSoumettre1;
    private javax.swing.JComboBox<String> cbMaterielVendu;
    private javax.swing.ButtonGroup groupRadioButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblNomClient;
    // End of variables declaration//GEN-END:variables
}
