/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject;

import javax.swing.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author raphaeltribouilloy
 */
public class SearchClient extends javax.swing.JFrame {

    private static javax.swing.JComboBox<String> cboxClient;
    private Client selectedClient;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContrat;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnXml;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;

    /**
     * Creates new form SearchClient
     */
    public SearchClient() throws SQLException {
        initComponents();
        connectionBDD();
    }

    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new SearchClient().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(SearchClient.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        //Establish connection
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboxClient = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnXml = new javax.swing.JButton();
        btnContrat = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nom du Client");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel2.setText("       CASHCASH");
        jLabel2.setToolTipText("");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cboxClient.addActionListener(this::comboActionPerformed);

        btnXml.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        btnXml.setText("XML");
        btnXml.addActionListener(this::btnXmlActionPerformed);

        btnContrat.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        btnContrat.setText("Contrat de Maintenance");

        btnPDF.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        btnPDF.setText("PDF");
        btnPDF.addActionListener(this::btnPDFActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel1)
                                                .addGap(89, 89, 89)
                                                .addComponent(cboxClient, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                        .addComponent(btnPDF)
                                                                        .addGap(119, 119, 119))
                                                                .addComponent(btnContrat, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                        .addComponent(btnXml)
                                                                        .addGap(113, 113, 113)))
                                                        .addGap(108, 108, 108))
                                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(cboxClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(btnXml)
                                .addGap(18, 18, 18)
                                .addComponent(btnContrat)
                                .addGap(18, 18, 18)
                                .addComponent(btnPDF)
                                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboActionPerformed(java.awt.event.ActionEvent e) {
        JComboBox cb = (JComboBox) e.getSource();
        String clientName = (String) cb.getSelectedItem();
        for (Client client : Client.getLesClients()) {
            if (client.getNom().equalsIgnoreCase(clientName)) {
                this.selectedClient = client;
                break;
            }
        }
    }

    private void btnXmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXmlActionPerformed
        // TODO add your handling code here:-
    }//GEN-LAST:event_btnXmlActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {
        new PDF(selectedClient);
    }

    /**
     * @param args the command line arguments
     */
    private void connectionBDD() throws SQLException {
        Connection connection = Connecting.getConnexion();

        System.out.println("\nRécupération des clients...");
        ResultSet result = connection.createStatement().executeQuery("SELECT * FROM client");
        while (result.next()) {
            String numClient = result.getString(1);
            String nom = result.getString(2);
            String raisonSociale = result.getString(3);
            String siren = result.getString(4);
            String codeApe = result.getString(5);
            String adresse = result.getString(6);
            String numTelephone = result.getString(7);
            String fax = result.getString(8);
            int dureeDeplacement = result.getInt(9);
            int distanceKm = result.getInt(10);
            String numAgence = result.getString(11);
            String url = result.getString(12);
            String logo = result.getString(13);

            new Client(
                numClient,
                raisonSociale,
                siren,
                codeApe,
                adresse,
                numTelephone,
                url,
                logo,
                numAgence,
                nom,
                dureeDeplacement,
                distanceKm
            );

            cboxClient.addItem(nom);
        }
        System.out.println("Clients récupérés : \u001B[36m" + Client.getLesClients().size() + "\u001B[0m.");
        TypeContrat.loadAllTypes();
    }
    // End of variables declaration//GEN-END:variables
}